### ISSUE TITLE
Project management video

### ISSUE THREAD

**Issue by ejiektpobehuk** [ejiek/TSD-g07-spec#4]
- [x] Write a script
- [x] Discuss script 
- [x] Demo run 
- [x] Record video 
- [x] Edit video 
- [x] Upload video to yt

**Comment by ejiek** [comment]
- [ ] Write a script
- [ ] Discuss script 
- [ ] Demo run 
- [ ] Record video 
- [ ] Edit video 
- [ ] Upload video to yt
